# Site
repository: dhkimxx/dhkimxx.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김도형 | Dohyeong Kim
title: Junior Full Stack Developer
email: dhkimxx@naver.com


# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  dhkimxx
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 도형-김-8b3526276
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: blog
  icon: fas fa-blog
  url: https://blog.naver.com/dhkimxx
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-kdh.png
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 주니어 풀스택 개발자로 활동하고 있는 김도형입니다. 웹 어플리케이션 기반의 사물인터넷, 대시보드, 리모트랩, 개발자 커뮤니티 등 다양한 분야의 서비스를 다루어 본 경험이 있으며, 
  개발자 커뮤니티 서비스 개발을 경험하면서 마이크로 서비스 아키텍처 기반의 백엔드 어플리케이션 개발에 관심을 갖고 있습니다.
  <br/>
  <br/>
  주요기술: <mark>Spring boot</mark>  <mark>React</mark> <mark>Docker</mark> <mark>MySQL</mark>

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ThunderSoft Korea
        link: https://kr.thundersoft.com/
        # link_text: boringcompany.com
        sub_title: Web Application developer
        caption: 2023.09 ~ 2024.01 (Internship), 2024.01 ~ Present
        quote: >
           Focus AI Camera Dashboard, Samsung Exynos Society ...

        description: | # this will include new lines to allow paragraphs
          - IoT Dashboard for Monitoring AI Camera Feed and Device Status 
            -  Development Web based camera feed streaming system using AWS KVS
            -  Development Backend server for collecting data pipeline of camera device status using AWS IoT

          - Samsung Exynos Society (Community for Developers)
            - Transition from a monolithic architecture in the existing legacy system to a modern microservices architecture
            - Development of a Markdown editor for developer users of the community forum


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tech University of Korea
        caption: 2018 - 2024
        sub_title: Bachelor of Science in Embedded System
        quote: # 한국공학대학교(Tech University of Korea)는 기술 인력 양성을 위해 대한민국 산업통상자원부가 출연하여 설립한 경기도 시흥시의 사립 대학이다. 영문 약칭은 TUKOREA이며, 국문 약칭으로 한국공대가 쓰인다. 산업통상자원부가 설립한 대학으로서 연구 및 실험실습의 비중이 큰 편이다.
        description: | # this will include new lines to allow paragraphs
          - 한국공학대학교에서 4년간 임베디드시스템을 공부해오면서 다양한 프로젝트에 참여하여 팀원들과의 협업을 통해 커뮤니케이션 능력 및 일정 관리 능력을 향상시킬 수 있었습니다.
          <br/><br/>
          - 낙상사고 예방을 위한 사물인터넷 시스템을 직접 설계 및 구축하는 졸업작품 프로젝트를 통해, RestAPI 및 MQTT 등 다양한 데이터 전송 기술을 다루어 보면서 웹 어플리케이션 개발자 로드맵을 시작하는 전환점이 될 수 있었습니다.
          <br/><br/>



  - title: Projects of Study  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left  # top-middle
        title: Smart Lamp for Fall Accident Prevention
        link: https://github.com/dhkimxx/smartLamp
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/dhkimxx/smartLamp\
        description: | 
          - Development of IoT System Using MQTT and HTTP protocol
          - Developed a smart lamp device using ESP8266, PWM driver, PIR sensor, and HC-SR04(Ultrasonic) sensor. 
          - Implement data communicative application through HTTP and MQTT protocols for a mobile application using the Flutter framework. 
          - Developing a backend server based on the Spring framework, enabling user registration, retrieval, modification, and deletion of device information. 

    
      - layout: left
        title: Smart Home IoT Project 
        description: | 
          - Implement smart home system using ESP32, st7789 display, DHT22 sensor, PIR sensor, and lux sensor. 
          - Developing monitoring environment with Node-RED, influxdb, and MQTT broker on an AWS EC2 Linux instance, along with service logic implementation. 
          - Enhancement Internet of Things security through asymmetric encryption methods. 


      - layout: left
        title: 2023 Techeer Ideathon Project
        description: | 
          - Developed a web application providing health club information and a community service based on user location. 
          - Backend server development utilizing the Spring framework and MySQL database. 

      
      - layout: left
        title: Data Analysis Projects
        description: | 
          - Developed a CNN-based VGGNet deep learning model for diagnosing ocular diseases based on images of dog and cat eyeballs. 
          - Developed a machine learning model using the Sklearn library to predict parking demand based on data such as apartment complex rent, security deposit, public transportation facilities, and parking area. 




  - title: Thank you for taking the time to read my resume. 
    layout: text
    content: | # this will include new lines to allow paragraphs
     
      ![cycling](/images/cycle.jpeg)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
